### ISSUE TITLE
Check whether a promises based API is doable

### ISSUE THREAD

**Issue by frivoal** [browserext/browserext#12]

**Comment by frivoal** [comment]
Meeting minutes: http://browserext.github.io/minutes/2016-09-22.html

**Comment by Rob--W** [comment]
Two things:
- In the minutes it is not clear whether you consider the possibility for promise-based APIs to be added to Chrome. Here is the relevant ticket where Chromium team members express a favorable attitude towards promises: https://crbug.com/328932.
- Adding promises does not necessarily negate the need for the `runtime.lastError` attribute, because it is currently the only way to signal errors in things such as events (e.g. `port.onDisconnect`).

**Comment by snoack** [comment]
For reference, there was a brief [discussion on the mailing list](https://lists.w3.org/Archives/Public/public-browserext/2016Oct/0002.html). To sum it up, it seems very feasible to use promises instead of callback, even without breaking backwards compatibility, like Firefox is already doing.

**Comment by kmaglione** [comment]
> Adding promises does not necessarily negate the need for the runtime.lastError attribute, because it is currently the only way to signal errors in things such as events (e.g. port.onDisconnect).

It's perfectly possible to signal errors to event listeners by passing them as arguments.

**Comment by mikepie1** [comment]
Approved Promises per meeting http://browserext.github.io/minutes/2017-02-02.html
Spec updated in Pull Request 44 https://github.com/browserext/browserext/pull/44
