### ISSUE TITLE
Discuss adding tabs.captureVisibleTab and onReplaced

### ISSUE THREAD

**Issue by mikepie1** [browserext/browserext#26]

**Comment by snoack** [comment]
> @kmaglione: I am not sure about onReplaced. We have it as a stub, but it is not backed by actual functionality. I don’t actually know when Chrome actually triggers it, the documentation is unclear.

When you type into the address bar, Chrome tries to predict which URL you are about to navigate to (based on your history). As soon as a suggestion shows up in the UI, a background tab is created loading that URL. While that tab isn't visible to the user, it is treated just like a new regular tab in the extension API, [except when it is not](https://github.com/adblockplus/adblockpluschrome/blob/dcc5b2f17330d9f33ad3dbe379de1e54a6489a97/chrome/ext/background.js#L271). When the user presses enter, that tab becomes visible, and replaces the tab shown before. For the user it looks like it is the same tab, but since it has a different `tabId`, any extension that keeps track of tabs needs to respond to this event using a `tabs.onReplaced` handler.

If your browser does pre-rendering (like Chrome does), and doesn't implement `tabs.onReplaced` and the related logic, there is no way for extensions to avoid an inconsistent state.

However, we might want to consider getting rid of the inconsistencies, which currently exist in Chrome, where the `tabId` of a pre-rendered tab is not accepted, by some methods, before the tab becomes visible.

> @shwetank: I haven’t seen people use it.

We (Adblock Plus) do, and AdBlock as well since they are using our code under the hood, nowadays.

**Comment by shwetank** [comment]
@snoack Thanks, thats interesting info and helpful.

**Comment by mikepie1** [comment]
Per meeting http://browserext.github.io/minutes/2016-10-20.html decided to keep captureVisibleTabs but not onChanged. Spec upadated in Pull Request 44 https://github.com/browserext/browserext/pull/44
