### ISSUE TITLE
Should we only support promisses only, or also handle callbacks?

### ISSUE THREAD

**Issue by frivoal** [browserext/browserext#38]
We have agreed that we would use a promise based design for the API under the `browser` namespace, and that using this, a polyfill could be written under the `chrome` namespace.

We have not yet agreed whether supporting callbacks instead of promises is something that would be up to the implementor of the polyfill, or if we should also support callbacks under the `browser` namespace and return promises only when the callback parameter is missing.

**Comment by snoack** [comment]
> a polyfill could be written under the `chrome` namespace.

I'm not sure whether such a polyfill should use the `chrome`, or should rather patch the `browser`, namespace. What is about code written for environments that have already the `browser` namespace but don't support promises yet (like Microsoft Edge at the moment)? Extension code that has been written for Chrome, on the other hand, can just define `var chrome = browser;`, when ported to other browsers.

> We have not yet agreed whether supporting callbacks instead of promises is something that would be up to the implementor of the polyfill, or if we should also support callbacks under the browser namespace and return promises only when the callback parameter is missing.

I think since all major implementors (i.e. Chrome, Firefox and Microsoft Edge) currently support the calling convention using callbacks (instead of, or additionally to, promises), and therefore virtually all existing extensions rely on it, it would be nice to preserve the old calling convention for backwards compatibility in those browsers, for now. However, as [discussed on the mailing list](https://lists.w3.org/Archives/Public/public-browserext/2016Oct/0002.html), we probably shouldn't spec the legacy calling convention in the standard.

For reference, this seems to be a duplicate (or a sub-discussion at least) of #12.

**Comment by frivoal** [comment]
If everybody should support callbacks, I think it should be specified. We can mark it as deprecated and encourage promises in the spec, but:
- Specifying it helps ironing out the little details that matter to interoperability
- If everybody implements callbacks extensions will depend on them. If extensions depend on them, any new browser will need to implement them as well. When you need to implement something, having a spec is much nicer.

If nobody will support callbacks under the browser namespace, and we just decide to leave the entire bridging of the chrome namespace to the browser namespace to a polyfill, then I suppose it is fine not to specify. But if we're actually planing to support callbacks in the browser namespace, I think there should be a spec.

**Comment by frivoal** [comment]
> For reference, this seems to be a duplicate (or a sub-discussion at least) of #12.

Yes, that's true. I suppose they're slightly different, since this discussion assumes the question raised in #12 has been answered positively, but they are certainly related.

**Comment by mikepie1** [comment]
Agreed to use Promises per meeting http://browserext.github.io/minutes/2017-02-02.html
Spec updated in Pull Request 44 https://github.com/browserext/browserext/pull/44
